# Generated by Django 4.2.6 on 2025-07-27 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatlog',
            old_name='bot_response',
            new_name='bot_reply',
        ),
        migrations.RenameField(
            model_name='chatlog',
            old_name='user_input',
            new_name='user_message',
        ),
    ]
